name: Laravel Workflow

on:
  push:
    branches:
      - main

jobs:
  laravel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12'  # Use a more recent and stable PHP version
          extensions: mysql
          coverage: xdebug

      - name: Create .env file
        run: |
          touch .env
          echo "APP_ENV=local" >> .env
          echo "APP_KEY=" >> .env
          echo "APP_DEBUG=true" >> .env
          echo "APP_URL=http://localhost" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=test" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=" >> .env

      - name: Get composer cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)"
          echo "##[set-output name=cache-dir;]$dir"

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.cache-dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: |
          composer install --no-dev --prefer-dist --optimize-autoloader
          composer dump-autoload -o  # Optimize autoloading

      - name: Prepare Laravel Application
        run: |
          php artisan key:generate
          php artisan config:cache
          php artisan storage:link
          php artisan optimize:clear
          php artisan migrate  # Run migrations
          php artisan db:seed --class=DatabaseSeeder  # Optional: run database seeder

      - name: Run Laravel Application
        run: php artisan serve --no-reload  # Run the application without reloading